SET NAMES 'utf8';

DROP TABLE IF EXISTS user;

DROP TABLE IF EXISTS profile;

DROP TABLE IF EXISTS balance;


CREATE TABLE IF NOT EXISTS user (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX UNIQ_8D93D649F85E0677 (username)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS profile (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  first_name VARCHAR(255) NOT NULL DEFAULT '',
  last_name VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  UNIQUE INDEX UNIQ_8157AA0FA76ED395 (user_id),
  CONSTRAINT FK_8157AA0FA76ED395 FOREIGN KEY (user_id)
    REFERENCES user(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS balance (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  amount DECIMAL(20, 8) NOT NULL DEFAULT 0.00000000,
  currency VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  INDEX IDX_ACF41FFEA76ED395 (user_id),
  CONSTRAINT FK_ACF41FFEA76ED395 FOREIGN KEY (user_id)
    REFERENCES user(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci
ROW_FORMAT = DYNAMIC;


LOCK TABLES user WRITE;
INSERT INTO user VALUES
(1, 'Test');
UNLOCK TABLES;

LOCK TABLES profile WRITE;
INSERT INTO profile VALUES
(1, 1, 'FirstName', 'LastName');
UNLOCK TABLES;

LOCK TABLES balance WRITE;
INSERT INTO balance VALUES
(1, 1, 100.00000000, 'USD'),
(2, 1, 2000.00000000, 'UAH');
UNLOCK TABLES;
